### ISSUE TITLE
Doesn't aggregate time over multiple tasks 

### ISSUE THREAD

**Issue by ukriish** [nilenso/time-graphs#1]
Only the time for the first task for a project ends up on the dashboard.

Eg:
* Foo - Development - 3H
* Foo - IPM - 20m
* Foo - Development - 4H
* Foo - Retro - 10m

I can only see the first one on the graph for 3H.

**Comment by ssrihari** [comment]
Fixed in 955c915d91a8a6db4f73edc8aac52661c068fe01.

**Comment by ssrihari** [comment]
Thanks @krish8664!
